[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/home"
  to = "/#home"
  status = 301

[[redirects]]
  from = "/sports"
  to = "/#sports-tours"
  status = 301

[[redirects]]
  from = "/golf"
  to = "/#golf"
  status = 301

[[redirects]]
  from = "/fan-packages"
  to = "/#fan-packages"
  status = 301

[[redirects]]
  from = "/adventure"
  to = "/#adventure"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301